import csv
import json
from collections import Counter
from pathlib import Path

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "sample_data.csv"
REPORT_PATH = Path(__file__).resolve().parent.parent / "reports" / "insights.txt"


def load_data():
    with open(DATA_PATH, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def analyze_skills(jobs):
    skill_counter = Counter()
    for job in jobs:
        for skill in job["skills"].split(","):
            skill_counter[skill.strip()] += 1
    return skill_counter.most_common(15)


def analyze_experience(jobs):
    exp_ranges = {"0-2": 0, "3-5": 0, "6-8": 0, "8+": 0}
    for job in jobs:
        exp = int(job["experience_years"])
        if exp <= 2:
            exp_ranges["0-2"] += 1
        elif exp <= 5:
            exp_ranges["3-5"] += 1
        elif exp <= 8:
            exp_ranges["6-8"] += 1
        else:
            exp_ranges["8+"] += 1
    return exp_ranges


def analyze_locations(jobs):
    return Counter(job["location"] for job in jobs).most_common()


def generate_report(jobs):
    top_skills = analyze_skills(jobs)
    exp_dist = analyze_experience(jobs)
    loc_dist = analyze_locations(jobs)

    report = []
    report.append("=" * 60)
    report.append("PS 26134 - SKILL DEVELOPMENT & INDUSTRY ALIGNMENT")
    report.append("Smart India Hackathon 2026 - Analysis Report")
    report.append("=" * 60)
    report.append(f"\nTotal Jobs Analyzed: {len(jobs)}")
    report.append(f"Unique Skills Found: {sum(1 for _ in set(s for j in jobs for s in j['skills'].split(',')))}")

    report.append("\n--- TOP SKILLS IN DEMAND ---")
    for skill, count in top_skills:
        pct = round(count / len(jobs) * 100, 1)
        report.append(f"  {skill:25s} : {count:2d} ({pct}%)")

    report.append("\n--- EXPERIENCE DISTRIBUTION ---")
    for range_name, count in exp_dist.items():
        pct = round(count / len(jobs) * 100, 1)
        report.append(f"  {range_name:10s} years : {count:2d} ({pct}%)")

    report.append("\n--- LOCATION DISTRIBUTION ---")
    for loc, count in loc_dist:
        pct = round(count / len(jobs) * 100, 1)
        report.append(f"  {loc:15s} : {count:2d} ({pct}%)")

    report.append("\n" + "=" * 60)
    report.append("Report generated by sih134/scripts/analyze.py")
    report.append("=" * 60)

    return "\n".join(report)


if __name__ == "__main__":
    jobs = load_data()
    report = generate_report(jobs)
    print(report)
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"\nReport saved to {REPORT_PATH}")
